<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2013-03-20 20:12

$extensionClassesPath = t3lib_extMgm::extPath('gc_dev') . 'Classes/';
return array(
	'tx_gcdev_pagetreecliformatter' => $extensionClassesPath . 'class.Tx_GcDev_PageTreeCLIFormatter.php',
	'tx_gcdev_tstemplatehelper' => $extensionClassesPath . 'class.Tx_GcDev_TSTemplateHelper.php',
);
?>